
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: actions-runner-system
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "c23647c0-2074-4565-8940-54e18057a0f0"
    azure.workload.identity/tenant-id: "01b41838-a123-48a9-9aaf-91a8d640ff68"