apiVersion: external-secrets.io/v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    azure.workload.identity/client-id: "508bcd98-5e4c-40e2-a68d-773035a263e5"
    azure.workload.identity/tenant-id: "01b41838-a123-48a9-9aaf-91a8d640ff68"