apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-secret 
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: github-app-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_token: "{{ .github_pat_token }}"
  data:
    - secretKey: github_pat_token
      remoteRef:
        key: gh_flux_aks_token