apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: azure-keyvault-store
    app.kubernetes.io/instance: actions-runner-system-store
spec:
  provider:
    azurekv:
      tenantId: "01b41838-a123-48a9-9aaf-91a8d640ff68"
      vaultUrl: "https://kv-myaks-tst-swn-00.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets