apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    azure.workload.identity/client-id: "18fe4943-5fb3-4157-acbd-53663dfa922d"
    azure.workload.identity/tenant-id: "01b41838-a123-48a9-9aaf-91a8d640ff68"

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
spec:
  provider:
    azurekv:
      tenantId: 01b41838-a123-48a9-9aaf-91a8d640ff68
      vaultUrl: https://kv-myaks-tst-swn-00.vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
