apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/actions-runner-system
  - ../../base/flux-system/repositories
  - ../../base/actions-runner-system/gha-runner-scale-set/ks.yaml
  - ../../base/actions-runner-system/gha-runner-scale-set-controller/ks.yaml