apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kubernetes/apps/base/actions-runner-system
  - ./kubernetes/apps/base/flux-system/repositories
  - ./kubernetes/apps/base/actions-runner-system/gha-runner-scale-set/ks.yaml
  - ./kubernetes/apps/base/actions-runner-system/gha-runner-scale-set-controller/ks.yaml