apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  type: oci
  url: oci://ghcr.io/external-secrets/external-secrets
  interval: 5m
  secretRef:
    name: ghcr-auth