apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/actions-runner-system

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: arc-runners
      spec:
        values:
          minRunners: 0
          maxRunners: 5
    target:
      kind: HelmRelease
      name: arc-runners