
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/overlays/aks-myaks-dev-swn-003
  prune: true
  wait: true
  healthcheck: []

  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: external-secrets
  #     namespace: external-secrets-system
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: external-secrets-webhook
  #     namespace: external-secrets-system
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: gha-runner-scale-set-controller
  #     namespace: arc-systems
  