
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-identity-injection
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/infrastructure/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  vars:
    - name: ESO_CLIENT_ID
      objRef:
        kind: Secret
        name: cluster-identity-client-ids
        apiVersion: v1
      valueFrom:
        key: external-secrets-client-id
    - name: ARC_CONTROLLER_CLIENT_ID
      objRef:
        kind: Secret
        name: cluster-identity-client-ids
        apiVersion: v1
      valueFrom:
        key: arc-controller-client-id
    - name: ARC_RUNNERS_CLIENT_ID
      objRef:
        kind: Secret
        name: cluster-identity-client-ids
        apiVersion: v1
      valueFrom:
        key: arc-runners-client-id
    - name: FLUX_CLIENT_ID
      objRef:
        kind: Secret
        name: cluster-identity-client-ids
        apiVersion: v1
      valueFrom:
        key: flux-client-id

  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-identity-client-ids