apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - infrastructure.yaml
  - apps.yaml
  - inject-identity-vars.yaml
