apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat-secret
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: github-pat-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: gh-flux-aks-token