apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-system
    app.kubernetes.io/part-of: github-runners
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    toolkit.fluxcd.io/tenant: workload