apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: actions-runner-system
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "${AZURE_KEYVAULT_URL}"
      serviceAccountRef:
        name: actions-runner-controller-manager